### ISSUE TITLE
org-mode headline faces

### ISSUE THREAD

**Issue by popcorn4dinner** [alphapapa/org-sticky-header#10]
Hi, 
I'm fairly new to emacs and org. I have been playing around with both org-sticky-header and org-super-agenda.
Everything works fine by now, but there is one thing I just cannot figure out: 
How can I make me entries in my org files look like the ones on the screenshots (with the line on top and the different font sizes, etc? 
Can you maybe paste a snippet of your settings?

Many thanks in advance!

**Comment by alphapapa** [comment]
Hi there,

Welcome to the Emacs and Org communities!  Turn back now, before it's too late!  Haha, just kidding, but they can be addictive once you start customizing things!  :)

Sure, here is the code I'm currently using.  This code runs in my init file and sets up the different `org-level-` headings.  This looks rather complicated, and it sort-of is, but it's not necessary to do it this way.  You can just set the `org-level-` and `outline-` headings directly, which is what I did for a long time until I put this function together recently.  The reasons for this function are to 1) easily define extra heading levels, besides the defaults; and 2) easily change the color sequence.  As you can see, this is specific to the Solarized theme, but you could easily change that.
```el
(cl-defun ap/org-set-level-faces (&key (first-parent 'outline-1))
    (solarized-with-color-variables 'dark
      (require 'color)
      (require 'dash)
      (require 'org-inlinetask)
      (let ((org-level-color-list (-cycle (list red orange yellow green cyan blue violet magenta))))
        (cl-flet ((modify-color (color) (thread-first color
                                          (color-desaturate-name 30))))
          (cl-loop for level from 1 to (1- org-inlinetask-min-level)
                   for face = (intern (format "org-level-%s" level))
                   for parent = (cl-case level
                                  (1 (list first-parent 'highlight))
                                  (t (intern (format "org-level-%s" (1- level)))))
                   for height = (cond ((= level 1) 1.3)
                                      ((<= level 4) 0.9)
                                      (t 1.0))
                   for weight = (if (<= level 8) 'bold 'normal)
                   unless (internal-lisp-face-p face)
                   do (custom-declare-face face `((t :inherit ,(intern (format "outline-%s" (1- level)))))
                                           (format "Face for Org level %s headings." (1- level)))
                   do (set-face-attribute face nil
                                          :inherit parent
                                          :foreground (modify-color (nth level org-level-color-list))
                                          :height height
                                          :weight weight
                                          :overline t)
                   collect face into faces
                   finally do (defconst org-level-faces faces)
                   finally do (setq org-n-level-faces (length org-level-faces)))))))
  (ap/org-set-level-faces :first-parent 'variable-pitch)
```
Hope this helps!  By the way, check out my other Org-related packages, you'll probably find them useful too.  :)

**Comment by popcorn4dinner** [comment]
Thanks for the warm welcome! 😃 

And yes, I have been spending quite some time trying to get things working the way I want. But boy, it's rewarding, when things finally jump in line... 
Oh, and I will certainly try some more of your packages. You seems to be doing a great job with those.
Your settings worked perfectly for me. I only replaced the colour names by hex codes. 
This might be a stupid question, but I expected the headlines in the agenda to look the same. Can you tell me why those were not effected?

**Comment by alphapapa** [comment]
In the agenda, headlines are not fontified the way they are in normal Org buffers.  Instead, colors are used to represent the status of items, e.g. deadline overdue, deadline approaching, etc.  This is all customizable (be sure to familiarize yourself with the `customize` interface if you haven't already, e.g. run `M-x customize-group RET org RET`, because it makes it easy to change settings and learn what settings exist).

It's an interesting idea, though, to fontify agenda headings similarly to how they are in their respective buffers.  You'd lose information about their status, but it would help show the level of headings.

**Comment by popcorn4dinner** [comment]
I will do that now :-)
And actually it makes a lot of sense that way. I just assumed it would, since the screen shots of both the sticky-headers headlines and the super-agenda headlines looked basically the same.
Again, thanks for your help!
If that's ok, I might be bothering you again with some newbie questions in the future..

**Comment by alphapapa** [comment]
I'm glad to help, but it would generally be better to ask in a place like www.reddit.com/r/emacs so that other people can also help, and so everyone can benefit from the answers.  If you post something there about one of my packages or Org mode, I'll most likely see it.

**Comment by alphapapa** [comment]
I think there's nothing more to do here, so closing.  Thanks.
