### ISSUE TITLE
Preference to set face for org-sticky-header that is different than normal headline.

### ISSUE THREAD

**Issue by mankoff** [alphapapa/org-sticky-header#15]
Would be nice to, for example, underline the sticky header, or invert colors, etc.

**Comment by alphapapa** [comment]
I'm not sure it would be worth the additional complexity to add this feature.  If you really want to, you could use function advice on `org-sticky-header--fetch-stickyline` in your Emacs config to apply more faces to the string.

**Comment by mankoff** [comment]
Will do. If I get around to this I'll post the code here.

**Comment by alphapapa** [comment]
Thanks.
