### ISSUE TITLE
Need an example of how one can set the outline mode

### ISSUE THREAD

**Issue by myTerminal** [alphapapa/org-sticky-header#16]
There's a mention in the README.md that one can change the outline mode and there are three options. However, there's no example of how this can be done.

I examined the code and found out that the below works:

    (setq org-sticky-header-full-path 'full)

I wouldn't call this an issue as such, but a simple example of how one can do that would really help new users.

I have proposed a change in [this pull-request](https://github.com/alphapapa/org-sticky-header/pull/17).

**Comment by alphapapa** [comment]
As I mentioned in #17, this is handled by Emacs's customization system.  Users shouldn't use `setq` for customization options; they should use the customization system.  This is a common misunderstanding.  You could also use `validate-setq` from https://elpa.gnu.org/packages/validate.html.

**Comment by myTerminal** [comment]
Cool, I'll close this one then. Thank you!
