### ISSUE TITLE
Repeting issues when everything is in display

### ISSUE THREAD

**Issue by sergiusens** [alphapapa/org-sticky-header#21]
I notice this issue I have a buffer being displayed where the entire buffer can be seen (no sticky header required), structured like:

```org
#+TITLE: title

* heading 1
** heading 1.1
** heading 1.2
```

I see a repeat of what follows in the message buffer:
```
Error during redisplay: (eval (progn (setq org-sticky-header-stickyline (propertize (org-sticky-header--fetch-stickyline) 'keymap org-sticky-header-keymap)) (list (propertize " " 'display '((space :align-to 0))) 'org-sticky-header-stickyline))) signaled (wrong-type-argument stringp nil) [64 times]
```

Those 64 times are were generated in about 64 seconds

**Comment by alphapapa** [comment]
Thanks, since those errors don't appear in the echo area, I've never noticed them myself.  I see them as well with the example you gave.

This appears to be the same as the issue reported in #19 and fixed in #20.
