### ISSUE TITLE
org-sticky headers is not enabled when opening new org file

### ISSUE THREAD

**Issue by vanangamudi** [alphapapa/org-sticky-header#26]
This is the configuration, but the org-sticky-header is not enabled. I have to manually run org-sticky-header-mode command to enable it, on every file I open.

```
** Org Sticky Headers
#+begin_src emacs-lisp
  (use-package org-sticky-header
    :config (add-hook 'org-mode-hook 'org-sticky-header-mode))
  (use-package org-table-sticky-header
    :config (add-hook 'org-mode-hook 'org-table-sticky-header-mode))
#+end_src

```

**Comment by alphapapa** [comment]
Works for me.  Seems like an Emacs configuration problem, which you haven't provided enough information to diagnose.  Please ask on an appropriate forum, like Reddit, IRC, Matrix, etc.
