### ISSUE TITLE
scrolling makes the header line dissapear

### ISSUE THREAD

**Issue by jmburgos** [alphapapa/org-sticky-header#6]
Hi Alphapapa... great idea for a package!  
I am having a bit of an issue.  When I open an org mode file, the header line appears and shows the correct heading.  But as soon as I scroll down past the end of the screen, the header line dissapears.  I am using org-sticky-header version 20170420.2114 and org mode 9.0.5.

**Comment by alphapapa** [comment]
Hi there,

Glad you're enjoying it!  Or trying to, at least...

I've pushed several commits today, and I think I've fixed this bug, so please update to the latest version and let me know how it goes.  If it still isn't working, please let me know a few more things, like what version of Emacs you're on, and the values of any of the options in this package you may have customized.

Thanks!

**Comment by jmburgos** [comment]
Ok, I give it another try, and still no luck.  The behaviour has not changed. I am using emacs 25.2.1 org-sticky-header version 20170422.2114 and org mode 9.0.6.  This is my configuration for the package:

(use-package org-sticky-header
  :after org
  :config
(setq org-sticky-header-full-path 'full)
(add-hook 'org-mode-hook 'org-sticky-header-mode))

**Comment by alphapapa** [comment]
Hi Julian,

Hm, sorry you're still having this problem.  I'm afraid I don't understand exactly what's happening.  You said it happens when you "scroll down past the end of the screen."  Could you give me a more specific example?  If you could provide an "ECM", that would help a lot.

Thanks.

**Comment by jmburgos** [comment]
Ok, at the end it seems that the issue was not with your package, but with my .emacs configuration.  I had some bug and the package was not being loaded into the org-mode hook.  Sorry for the noise, and thanks for the help. :)
